### PR TITLE
Do not define __attribute__((constructor)) on MSVC

### PR DESCRIPTION
**Pull request by jcelerier**
it's not supported there

### CODE REVIEW

**Comment by x42** [comment]
How does compilation fail without this?

There is a `#if _MSC_VER && !__INTEL_COMPILER` from an earlier effort to port this to MSVC and it seems to work just fine -- Ardour compiles with MSVC and  `__attribute__((constructor))`, but I cannot test this myself.  Perhaps it depends on the version?

**Comment by jcelerier** [comment]
> How does compilation fail without this? 

    c:\users\blah\score\api\3rdparty\weakjack\weak_libjack.c(96): error C2065: 'constructor': undeclared identifier [C:\Users\blah\score-rel-64\API\OSSIA\ossia.vcxproj]
    c:\users\blah\score\api\3rdparty\weakjack\weak_libjack.c(96): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int [C:\Users\blah\score-rel-64\API\OSSIA\ossia.vcxproj]
    c:\users\blah\score\api\3rdparty\weakjack\weak_libjack.c(97): error C2448: '__attribute__': function-style initializer appears to be a function definition [C:\Users\blah\score-rel-64\API\OSSIA\ossia.vcxproj]

> There is a #if _MSC_VER && !__INTEL_COMPILER

it does not seem to cover this part though

**Comment by x42** [comment]
Odd that it does apparently work for Ardour.. -- the other MSVC & ! intel fix came from there...

Anyway it won't hurt to apply this. `init_weak_jack` is idempotent and will also be called from `jack_client_open()`

**Comment by x42** [comment]
Thanks for your contribution!

**Comment by jcelerier** [comment]
thanks!

**Pull request merged**
